Use logging based approach
Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>

diff --git a/etc/wrapper-clang++ b/etc/wrapper-clang++
--- a/etc/wrapper-clang++
+++ b/etc/wrapper-clang++
@@ -6,12 +6,26 @@
 # 1. Create two symlinks to this file: wrapper-clang and wrapper-clang++
 # 2. export TARGET_CC=/path/to/wrapper-clang
 #    export TARGET_CXX=/path/to/wrapper-clang++
-# 3. Run ./mach build --release
+#    export MOZJS_FROM_SOURCE <- to avoid using prebuilt mozjs artifact.
+# 3. Run ./mach build --release (or other optimising build profile)
 
+
+
+LOG_FILE=/Users/jschwender/Dev/servo/build-script-issues.txt
+FAIL_BUILD=false
 LLVM_BIN_PATH=/usr/bin
 #LLVM_BIN_PATH="/Users/jschwender/Applications/DevEco-Studio.app/Contents/sdk/default/openharmony/native/llvm/bin"
 REAL_CLANG_PATH="${LLVM_BIN_PATH}/clang"
 REAL_CLANGCPP_PATH="${LLVM_BIN_PATH}/clang++"
+
+# Pending better name. Actually does not fail build if FAIL_BUILD is not true-ish
+fail_build() {
+  case "${FAIL_BUILD:-}" in
+    1|true|TRUE|yes|YES|on|ON)
+      exit 1
+      ;;
+  esac
+}
 
 # We use the same wrapper for clang and clang++, so we check the symlink name
 # to determine which executable to dispatch to.
@@ -39,6 +53,10 @@ do
     elif [[ "${flag}" =~ aws-lc-sys-.*/aws-lc/tests/.*\.c(pp)?$ ]]; then
         skip_check="SKIP"
         break
+    elif [[ "${flag}" =~ aws-lc-sys-.*/jitterentropy/jitterentropy-library/src/jitterentropy-.*.c$ ]]; then
+        # Apparently this library purposefully requires `-O0`
+        skip_check="SKIP"
+        break
     elif [[ "${flag}" == "-Wl,"* ]]; then
          skip_check="SKIP"
          break
@@ -49,19 +67,23 @@ do
     fi
 done
 
+if [[ "$*" == "--version" || "$*" == "--print-prog-name"* || "$*" == "-?" ]]; then
+  skip_check="SKIP"
+fi
+
 if [[ "${skip_check}" == "SKIP" ]]; then
     # Don't care about opt level
     :
 elif [[ "${opt_level}" == "-Ofast" ]]; then
-    >&2 echo "clang was supposed to be invoked with -Ofast! We want standard compliance."
-    >&2 echo "All options: " "$@"
-    exit 1
+    echo "clang was supposed to be invoked with -Ofast! We want standard compliance." >> "${LOG_FILE}"
+    echo "All options: " "$@" >> "${LOG_FILE}"
+    fail_build
 elif [[ "${opt_level}" == "-O0" || "${opt_level}" == "" || "${opt_level}" == "-O" || "${opt_level}" == "-Og" ]]; then
-    >&2 echo "Source files should be compiled in release mode, but optimizations were disabled!"
-    exit 1
+    echo "Optimisations were disabled: " "$@" >> "${LOG_FILE}"
+    fail_build
 elif [[ "${opt_level}" == "-O1" ]]; then
-  >&2 echo "Warning: Source files will be compiled with -O1"
-  exit 1
+  echo "Warning: Source files will be compiled with -O1: "  "$@" >> "${LOG_FILE}"
+  fail_build
 fi
 
 # echo "Last opt level was: ${opt_level}"
